/* tslint:disable */
/* eslint-disable */
/*
Oxford Dictionaries

Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

The version of the OpenAPI document: 1.11.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { SentencesResults } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * TheSentenceDictionaryApi - axios parameter creator
 * @export
 */
export const TheSentenceDictionaryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *  Use this to retrieve sentences extracted from  corpora which show how a word is used in the language. This is available for English and Spanish. For English, the sentences are linked to the correct [sense](documentation/glossary?term=sense) of the word in the dictionary. In Spanish, they are linked at the [headword](documentation/glossary?term=headword) level.   <div id=\"sentences\"></div> 
         * @summary Retrieve corpus sentences for a given word
         * @param {'en' | 'es'} sourceLanguage IANA language code
         * @param {string} wordId An Entry identifier. Case-sensitive.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCorpusSentences: async (sourceLanguage: 'en' | 'es', wordId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sourceLanguage' is not null or undefined
            assertParamExists('getCorpusSentences', 'sourceLanguage', sourceLanguage)
            // verify required parameter 'wordId' is not null or undefined
            assertParamExists('getCorpusSentences', 'wordId', wordId)
            const localVarPath = `/entries/{source_language}/{word_id}/sentences`
                .replace(`{${"source_language"}}`, encodeURIComponent(String(sourceLanguage !== undefined ? sourceLanguage : `-source_language-`)))
                .replace(`{${"word_id"}}`, encodeURIComponent(String(wordId !== undefined ? wordId : `-word_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication appId required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "app_id", keyParamName: "appId", configuration })
            // authentication appKey required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "app_key", keyParamName: "appKey", configuration })

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/entries/{source_language}/{word_id}/sentences',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TheSentenceDictionaryApi - functional programming interface
 * @export
 */
export const TheSentenceDictionaryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TheSentenceDictionaryApiAxiosParamCreator(configuration)
    return {
        /**
         *  Use this to retrieve sentences extracted from  corpora which show how a word is used in the language. This is available for English and Spanish. For English, the sentences are linked to the correct [sense](documentation/glossary?term=sense) of the word in the dictionary. In Spanish, they are linked at the [headword](documentation/glossary?term=headword) level.   <div id=\"sentences\"></div> 
         * @summary Retrieve corpus sentences for a given word
         * @param {TheSentenceDictionaryApiGetCorpusSentencesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCorpusSentences(requestParameters: TheSentenceDictionaryApiGetCorpusSentencesRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SentencesResults>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCorpusSentences(requestParameters.sourceLanguage, requestParameters.wordId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TheSentenceDictionaryApi - factory interface
 * @export
 */
export const TheSentenceDictionaryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TheSentenceDictionaryApiFp(configuration)
    return {
        /**
         *  Use this to retrieve sentences extracted from  corpora which show how a word is used in the language. This is available for English and Spanish. For English, the sentences are linked to the correct [sense](documentation/glossary?term=sense) of the word in the dictionary. In Spanish, they are linked at the [headword](documentation/glossary?term=headword) level.   <div id=\"sentences\"></div> 
         * @summary Retrieve corpus sentences for a given word
         * @param {TheSentenceDictionaryApiGetCorpusSentencesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCorpusSentences(requestParameters: TheSentenceDictionaryApiGetCorpusSentencesRequest, options?: AxiosRequestConfig): AxiosPromise<SentencesResults> {
            return localVarFp.getCorpusSentences(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getCorpusSentences operation in TheSentenceDictionaryApi.
 * @export
 * @interface TheSentenceDictionaryApiGetCorpusSentencesRequest
 */
export type TheSentenceDictionaryApiGetCorpusSentencesRequest = {
    
    /**
    * IANA language code
    * @type {'en' | 'es'}
    * @memberof TheSentenceDictionaryApiGetCorpusSentences
    */
    readonly sourceLanguage: 'en' | 'es'
    
    /**
    * An Entry identifier. Case-sensitive.
    * @type {string}
    * @memberof TheSentenceDictionaryApiGetCorpusSentences
    */
    readonly wordId: string
    
}

/**
 * TheSentenceDictionaryApiGenerated - object-oriented interface
 * @export
 * @class TheSentenceDictionaryApiGenerated
 * @extends {BaseAPI}
 */
export class TheSentenceDictionaryApiGenerated extends BaseAPI {
    /**
     *  Use this to retrieve sentences extracted from  corpora which show how a word is used in the language. This is available for English and Spanish. For English, the sentences are linked to the correct [sense](documentation/glossary?term=sense) of the word in the dictionary. In Spanish, they are linked at the [headword](documentation/glossary?term=headword) level.   <div id=\"sentences\"></div> 
     * @summary Retrieve corpus sentences for a given word
     * @param {TheSentenceDictionaryApiGetCorpusSentencesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TheSentenceDictionaryApiGenerated
     */
    public getCorpusSentences(requestParameters: TheSentenceDictionaryApiGetCorpusSentencesRequest, options?: AxiosRequestConfig) {
        return TheSentenceDictionaryApiFp(this.configuration).getCorpusSentences(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
