/*
Oxford Dictionaries

Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

The version of the OpenAPI document: 1.11.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * cross references of a sense
 * @export
 * @interface CrossReferencesListInner
 */
export interface CrossReferencesListInner {
    /**
     * The word id of cooccurrence
     * @type {string}
     * @memberof CrossReferencesListInner
     */
    'id': string;
    /**
     * The word of cooccurrence
     * @type {string}
     * @memberof CrossReferencesListInner
     */
    'text': string;
    /**
     * The type of relation between the two words. Possible values are \'close match\', \'related\', \'see also\', \'variant spelling\', and \'abbreviation\' in case of crossreferences, or \'pre\', \'post\' in case of collocates.
     * @type {string}
     * @memberof CrossReferencesListInner
     */
    'type': string;
}

