/*
Oxford Dictionaries

Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

The version of the OpenAPI document: 1.11.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CategorizedTextListInner } from './categorized-text-list-inner';
import { GrammaticalFeaturesListInner } from './grammatical-features-list-inner';
import { PronunciationsListInner } from './pronunciations-list-inner';
import { Sense } from './sense';
import { VariantFormsListInner } from './variant-forms-list-inner';

/**
 * 
 * @export
 * @interface Entry
 */
export interface Entry {
    /**
     * 
     * @type {Array<string>}
     * @memberof Entry
     */
    'etymologies'?: Array<string>;
    /**
     * The different forms are correlated with meanings or functions which we text as \'features\'
     * @type {Array<GrammaticalFeaturesListInner>}
     * @memberof Entry
     */
    'grammaticalFeatures'?: Array<GrammaticalFeaturesListInner>;
    /**
     * Identifies the homograph grouping. The last two digits identify different entries of the same homograph. The first one/two digits identify the homograph number.
     * @type {string}
     * @memberof Entry
     */
    'homographNumber'?: string;
    /**
     * various types of notes that appear
     * @type {Array<CategorizedTextListInner>}
     * @memberof Entry
     */
    'notes'?: Array<CategorizedTextListInner>;
    /**
     * A list of possible pronunciations of a word
     * @type {Array<PronunciationsListInner>}
     * @memberof Entry
     */
    'pronunciations'?: Array<PronunciationsListInner>;
    /**
     * Complete list of senses
     * @type {Array<Sense>}
     * @memberof Entry
     */
    'senses'?: Array<Sense>;
    /**
     * Various words that are used interchangeably depending on the context, e.g \'aluminium\' and \'aluminum\'
     * @type {Array<VariantFormsListInner>}
     * @memberof Entry
     */
    'variantForms'?: Array<VariantFormsListInner>;
}

