/*
Oxford Dictionaries

Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

The version of the OpenAPI document: 1.11.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CategorizedTextListInner } from './categorized-text-list-inner';
import { TranslationsListInner } from './translations-list-inner';

/**
 * 
 * @export
 * @interface ExamplesListInner
 */
export interface ExamplesListInner {
    /**
     * 
     * @type {Array<string>}
     * @memberof ExamplesListInner
     */
    'definitions'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExamplesListInner
     */
    'domains'?: Array<string>;
    /**
     * various types of notes that appear
     * @type {Array<CategorizedTextListInner>}
     * @memberof ExamplesListInner
     */
    'notes'?: Array<CategorizedTextListInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExamplesListInner
     */
    'regions'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExamplesListInner
     */
    'registers'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExamplesListInner
     */
    'senseIds'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ExamplesListInner
     */
    'text': string;
    /**
     * A list of written or spoken rendering of the meaning of a word or text in another language(s)
     * @type {Array<TranslationsListInner>}
     * @memberof ExamplesListInner
     */
    'translations'?: Array<TranslationsListInner>;
}

