/*
Oxford Dictionaries

Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

The version of the OpenAPI document: 1.11.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FiltersResults } from './filters-results';

/**
 * Schema for the Filters endpoint.
 * @export
 * @interface Filters
 */
export interface Filters {
    /**
     * Additional Information provided by OUP
     * @type {object}
     * @memberof Filters
     */
    'metadata'?: object;
    /**
     * 
     * @type {FiltersResults}
     * @memberof Filters
     */
    'results'?: FiltersResults;
}

