/*
Oxford Dictionaries

Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

The version of the OpenAPI document: 1.11.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ThesaurusLexicalEntry } from './thesaurus-lexical-entry';

/**
 * description of thesaurus information of a word
 * @export
 * @interface HeadwordThesaurus
 */
export interface HeadwordThesaurus {
    /**
     * The identifier of a word
     * @type {string}
     * @memberof HeadwordThesaurus
     */
    'id': string;
    /**
     * IANA language code
     * @type {string}
     * @memberof HeadwordThesaurus
     */
    'language': string;
    /**
     * A grouping of various senses in a specific language, and a lexical category that relates to a word
     * @type {Array<ThesaurusLexicalEntry>}
     * @memberof HeadwordThesaurus
     */
    'lexicalEntries': Array<ThesaurusLexicalEntry>;
    /**
     * The json object type. Could be \'headword\', \'inflection\' or \'phrase\'
     * @type {string}
     * @memberof HeadwordThesaurus
     */
    'type'?: string;
    /**
     * A given written or spoken realisation of a an entry, lowercased.
     * @type {string}
     * @memberof HeadwordThesaurus
     */
    'word': string;
}

