/*
Oxford Dictionaries

Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

The version of the OpenAPI document: 1.11.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GrammaticalFeaturesListInner } from './grammatical-features-list-inner';
import { InflectionsListInner } from './inflections-list-inner';

/**
 * Description of an entry for a particular part of speech and grammatical features
 * @export
 * @interface LemmatronLexicalEntry
 */
export interface LemmatronLexicalEntry {
    /**
     * The different forms are correlated with meanings or functions which we text as \'features\'
     * @type {Array<GrammaticalFeaturesListInner>}
     * @memberof LemmatronLexicalEntry
     */
    'grammaticalFeatures'?: Array<GrammaticalFeaturesListInner>;
    /**
     * A grouping of the modifications of a word to express different grammatical categories
     * @type {Array<InflectionsListInner>}
     * @memberof LemmatronLexicalEntry
     */
    'inflectionOf': Array<InflectionsListInner>;
    /**
     * IANA language code
     * @type {string}
     * @memberof LemmatronLexicalEntry
     */
    'language': string;
    /**
     * A linguistic category of words (or more precisely lexical items), generally defined by the syntactic or morphological behaviour of the lexical item in question, such as noun or verb
     * @type {string}
     * @memberof LemmatronLexicalEntry
     */
    'lexicalCategory': string;
    /**
     * A given written or spoken realisation of a an entry.
     * @type {string}
     * @memberof LemmatronLexicalEntry
     */
    'text': string;
}

