/*
Oxford Dictionaries

Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

The version of the OpenAPI document: 1.11.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ArrayOfRelatedEntriesInner } from './array-of-related-entries-inner';
import { CategorizedTextListInner } from './categorized-text-list-inner';
import { Entry } from './entry';
import { GrammaticalFeaturesListInner } from './grammatical-features-list-inner';
import { PronunciationsListInner } from './pronunciations-list-inner';
import { VariantFormsListInner } from './variant-forms-list-inner';

/**
 * Description of an entry for a particular part of speech
 * @export
 * @interface LexicalEntry
 */
export interface LexicalEntry {
    /**
     * A list of written or spoken words
     * @type {Array<ArrayOfRelatedEntriesInner>}
     * @memberof LexicalEntry
     */
    'derivativeOf'?: Array<ArrayOfRelatedEntriesInner>;
    /**
     * A list of written or spoken words
     * @type {Array<ArrayOfRelatedEntriesInner>}
     * @memberof LexicalEntry
     */
    'derivatives'?: Array<ArrayOfRelatedEntriesInner>;
    /**
     * 
     * @type {Array<Entry>}
     * @memberof LexicalEntry
     */
    'entries'?: Array<Entry>;
    /**
     * The different forms are correlated with meanings or functions which we text as \'features\'
     * @type {Array<GrammaticalFeaturesListInner>}
     * @memberof LexicalEntry
     */
    'grammaticalFeatures'?: Array<GrammaticalFeaturesListInner>;
    /**
     * IANA language code
     * @type {string}
     * @memberof LexicalEntry
     */
    'language': string;
    /**
     * A linguistic category of words (or more precisely lexical items), generally defined by the syntactic or morphological behaviour of the lexical item in question, such as noun or verb
     * @type {string}
     * @memberof LexicalEntry
     */
    'lexicalCategory': string;
    /**
     * various types of notes that appear
     * @type {Array<CategorizedTextListInner>}
     * @memberof LexicalEntry
     */
    'notes'?: Array<CategorizedTextListInner>;
    /**
     * A list of possible pronunciations of a word
     * @type {Array<PronunciationsListInner>}
     * @memberof LexicalEntry
     */
    'pronunciations'?: Array<PronunciationsListInner>;
    /**
     * A given written or spoken realisation of a an entry.
     * @type {string}
     * @memberof LexicalEntry
     */
    'text': string;
    /**
     * Various words that are used interchangeably depending on the context, e.g \'aluminium\' and \'aluminum\'
     * @type {Array<VariantFormsListInner>}
     * @memberof LexicalEntry
     */
    'variantForms'?: Array<VariantFormsListInner>;
}

