/*
Oxford Dictionaries

Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

The version of the OpenAPI document: 1.11.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SynonymsAntonymsInner
 */
export interface SynonymsAntonymsInner {
    /**
     * 
     * @type {Array<string>}
     * @memberof SynonymsAntonymsInner
     */
    'domains'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SynonymsAntonymsInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof SynonymsAntonymsInner
     */
    'language'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SynonymsAntonymsInner
     */
    'regions'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SynonymsAntonymsInner
     */
    'registers'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SynonymsAntonymsInner
     */
    'text': string;
}

