/*
Oxford Dictionaries

Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

The version of the OpenAPI document: 1.11.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExamplesListInner } from './examples-list-inner';
import { SynonymsAntonymsInner } from './synonyms-antonyms-inner';

/**
 * A lexical sense represents the lexical meaning of a lexical entry when interpreted as referring to the corresponding ontology element
 * @export
 * @interface ThesaurusSense
 */
export interface ThesaurusSense {
    /**
     * 
     * @type {Array<SynonymsAntonymsInner>}
     * @memberof ThesaurusSense
     */
    'antonyms'?: Array<SynonymsAntonymsInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ThesaurusSense
     */
    'domains'?: Array<string>;
    /**
     * A list of written or spoken rendering of examples of use of a word or text
     * @type {Array<ExamplesListInner>}
     * @memberof ThesaurusSense
     */
    'examples'?: Array<ExamplesListInner>;
    /**
     * The id of the sense that is required for the delete procedure
     * @type {string}
     * @memberof ThesaurusSense
     */
    'id'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ThesaurusSense
     */
    'regions'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ThesaurusSense
     */
    'registers'?: Array<string>;
    /**
     * subsenses of word
     * @type {Array<ThesaurusSense>}
     * @memberof ThesaurusSense
     */
    'subsenses'?: Array<ThesaurusSense>;
    /**
     * 
     * @type {Array<SynonymsAntonymsInner>}
     * @memberof ThesaurusSense
     */
    'synonyms'?: Array<SynonymsAntonymsInner>;
}

