/*
Oxford Dictionaries

Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

The version of the OpenAPI document: 1.11.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ThesaurusEntry } from './thesaurus-entry';
import { VariantFormsListInner } from './variant-forms-list-inner';

/**
 * Description of an entry for a particular part of speech
 * @export
 * @interface ThesaurusLexicalEntry
 */
export interface ThesaurusLexicalEntry {
    /**
     * 
     * @type {Array<ThesaurusEntry>}
     * @memberof ThesaurusLexicalEntry
     */
    'entries'?: Array<ThesaurusEntry>;
    /**
     * IANA language code
     * @type {string}
     * @memberof ThesaurusLexicalEntry
     */
    'language': string;
    /**
     * A linguistic category of words (or more precisely lexical items), generally defined by the syntactic or morphological behaviour of the lexical item in question, such as noun or verb
     * @type {string}
     * @memberof ThesaurusLexicalEntry
     */
    'lexicalCategory': string;
    /**
     * A given written or spoken realisation of a an entry.
     * @type {string}
     * @memberof ThesaurusLexicalEntry
     */
    'text': string;
    /**
     * Various words that are used interchangeably depending on the context, e.g \'aluminium\' and \'aluminum\'
     * @type {Array<VariantFormsListInner>}
     * @memberof ThesaurusLexicalEntry
     */
    'variantForms'?: Array<VariantFormsListInner>;
}

