/*
Oxford Dictionaries

Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

The version of the OpenAPI document: 1.11.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ThesaurusSense } from './thesaurus-sense';
import { VariantFormsListInner } from './variant-forms-list-inner';

/**
 * 
 * @export
 * @interface ThesaurusEntry
 */
export interface ThesaurusEntry {
    /**
     * Identifies the homograph grouping. The last two digits identify different entries of the same homograph. The first one/two digits identify the homograph number.
     * @type {string}
     * @memberof ThesaurusEntry
     */
    'homographNumber'?: string;
    /**
     * Complete list of senses
     * @type {Array<ThesaurusSense>}
     * @memberof ThesaurusEntry
     */
    'senses'?: Array<ThesaurusSense>;
    /**
     * Various words that are used interchangeably depending on the context, e.g \'aluminium\' and \'aluminum\'
     * @type {Array<VariantFormsListInner>}
     * @memberof ThesaurusEntry
     */
    'variantForms'?: Array<VariantFormsListInner>;
}

