/*
Oxford Dictionaries

Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

The version of the OpenAPI document: 1.11.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Link to a sense of a specific entry in the thesaurus Dictionary
 * @export
 * @interface ThesaurusLink
 */
export interface ThesaurusLink {
    /**
     * identifier of a word
     * @type {string}
     * @memberof ThesaurusLink
     */
    'entry_id': string;
    /**
     * identifier of a sense
     * @type {string}
     * @memberof ThesaurusLink
     */
    'sense_id': string;
}

