/*
Oxford Dictionaries

Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

The version of the OpenAPI document: 1.11.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CategorizedTextListInner } from './categorized-text-list-inner';
import { GrammaticalFeaturesListInner } from './grammatical-features-list-inner';

/**
 * 
 * @export
 * @interface TranslationsListInner
 */
export interface TranslationsListInner {
    /**
     * 
     * @type {Array<string>}
     * @memberof TranslationsListInner
     */
    'domains'?: Array<string>;
    /**
     * The different forms are correlated with meanings or functions which we text as \'features\'
     * @type {Array<GrammaticalFeaturesListInner>}
     * @memberof TranslationsListInner
     */
    'grammaticalFeatures'?: Array<GrammaticalFeaturesListInner>;
    /**
     * IANA language code specifying the language of the translation
     * @type {string}
     * @memberof TranslationsListInner
     */
    'language': string;
    /**
     * various types of notes that appear
     * @type {Array<CategorizedTextListInner>}
     * @memberof TranslationsListInner
     */
    'notes'?: Array<CategorizedTextListInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TranslationsListInner
     */
    'regions'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TranslationsListInner
     */
    'registers'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TranslationsListInner
     */
    'text': string;
}

